{
  "openapi": "3.0.0",
  "info": {
    "title": "ProcureLive",
    "version": "1.0",
    "description": "APIs for procure live application"
  },
  "servers": [
    {
      "url": "http://localhost:3000/apis/procure-plus",
      "description": "Base URL"
    }
  ],
  "paths": {
    "/purchase-orders": {
      "get": {
        "summary": "Get Purchase Orders",
        "tags": [],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "examples": {
                  "Example Response": {
                    "value": {
                      "count": 1,
                      "purchase_orders": [
                        {
                          "id": 33904,
                          "number": "<Your PO Number>",
                          "pretty_id": "BZPO-15574-33904",
                          "placed_from": "procure_plus",
                          "created_at": "2020-06-03T00:12:38.521+05:30",
                          "updated_at": "2020-06-03T00:12:39.188+05:30",
                          "file": "http://demo.bizongo.in/downloads/purchase_orders?token=SampleToken",
                          "po_date": "2020-05-23T05:30:00.000+05:30",
                          "confirmation_mode": "erp",
                          "status": "open",
                          "placed_for": "Babulal Meena",
                          "user_id": 25558,
                          "billing_address": {
                            "id": 18812,
                            "cst": null,
                            "vat": null,
                            "city": "Ernakulam",
                            "alias": "COKF",
                            "gstin": "78AAICA5016B1ZE",
                            "state": "Kerala",
                            "country": "India",
                            "pincode": 682025,
                            "user_id": 32819,
                            "landmark": null,
                            "latitude": null,
                            "centre_id": 17702,
                            "full_name": "Wile E Coyote",
                            "is_active": true,
                            "longitude": null,
                            "country_id": 105,
                            "created_at": "2019-05-24T11:56:15.124+05:30",
                            "is_billing": true,
                            "state_code": "KL",
                            "updated_at": "2020-05-18T16:16:24.097+05:30",
                            "auto_fetched": false,
                            "company_name": "Acme Corporation",
                            "mobile_number": "9820098200",
                            "addressable_id": null,
                            "street_address": "Somewhere on planet earth, ",
                            "landline_number": "",
                            "addressable_type": null,
                            "alternate_number": "",
                            "gstin_state_code": "32",
                            "gstin_attachment_id": null,
                            "buyer_warehouse_code": null,
                            "nearest_warehouse_id": null,
                            "mobile_number_country_id": 105
                          },
                          "delivery_address": null,
                          "purchase_order_value": 2.36,
                          "ordered_value": 0,
                          "buyer": "Acme Corporation",
                          "centre": {
                            "id": 17702,
                            "name": "Acme South",
                            "is_hq": false,
                            "is_active": true
                          },
                          "creator": {
                            "id": 25558,
                            "name": "Wile E Coyote",
                            "type": "user"
                          },
                          "purchase_order_item_count": 1,
                          "total_quantity": 1,
                          "total_open_quantity": 1,
                          "total_delivered_quantity": 0
                        }
                      ]
                    }
                  }
                }
              }
            }
          },
          "": {
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "examples": {
                  "example-1": {}
                }
              }
            }
          }
        },
        "operationId": "get-procure-plus-purchase-orders",
        "description": "",
        "parameters": [
          {
            "schema": {
              "type": "integer"
            },
            "in": "query",
            "name": "page",
            "description": "Page number\n"
          },
          {
            "schema": {
              "type": "integer"
            },
            "in": "query",
            "name": "per_page",
            "description": "Page Size"
          }
        ]
      },
      "parameters": [],
      "post": {
        "summary": "Create Purchase Order with Delivery Requests",
        "operationId": "post-purchase-orders",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "purchase_order": {
                      "type": "object",
                      "required": [
                        "id",
                        "encrypted_file_url",
                        "confirmation_mode"
                      ],
                      "properties": {
                        "id": {
                          "type": "number"
                        },
                        "encrypted_file_url": {
                          "type": "string"
                        },
                        "number": {
                          "type": "string"
                        },
                        "pretty_id": {
                          "type": "string"
                        },
                        "confirmation_mode": {
                          "type": "string"
                        }
                      }
                    },
                    "delivery_group": {
                      "type": "object",
                      "required": [
                        "id",
                        "pretty_id",
                        "request_type"
                      ],
                      "properties": {
                        "id": {
                          "type": "number"
                        },
                        "pretty_id": {
                          "type": "string"
                        },
                        "request_type": {
                          "type": "string"
                        }
                      }
                    }
                  },
                  "required": [
                    "purchase_order",
                    "delivery_group"
                  ]
                },
                "examples": {
                  "Example": {
                    "value": {
                      "purchase_order": {
                        "id": 29688,
                        "encrypted_file_url": "http://qa1.indopus.in/downloads/purchase_orders?token=s4mpl3t0k3n",
                        "number": "BZPO-8131-29688",
                        "pretty_id": "BZPO-8131-29688",
                        "confirmation_mode": "erp"
                      },
                      "delivery_group": {
                        "id": 38929,
                        "pretty_id": "1588929462",
                        "request_type": "immediate"
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "description": "Create a single purchase order with one or many delivery requests. A delivery request is a unique grouping of a delivery date & shipping address id. A delivery group is a set of delivery requests placed together.",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "purchase_order": {
                    "type": "object",
                    "description": "Always use \"erp\"",
                    "required": [
                      "confirmation_mode",
                      "number",
                      "billing_address_id",
                      "request_type",
                      "items"
                    ],
                    "properties": {
                      "confirmation_mode": {
                        "type": "string",
                        "enum": [
                          "erp"
                        ]
                      },
                      "number": {
                        "type": "string",
                        "example": "ACME-0122811"
                      },
                      "billing_address_id": {
                        "type": "number",
                        "example": 762251,
                        "description": "Billing address ID of the address from Bizongo"
                      },
                      "request_type": {
                        "type": "string",
                        "enum": [
                          "immediate"
                        ]
                      },
                      "items": {
                        "type": "array",
                        "items": {
                          "type": "object",
                          "properties": {
                            "child_product_id": {
                              "type": "integer"
                            },
                            "total_quantity": {
                              "type": "number"
                            }
                          },
                          "required": [
                            "child_product_id",
                            "total_quantity"
                          ]
                        }
                      }
                    }
                  },
                  "delivery_requests": {
                    "type": "array",
                    "items": {
                      "type": "object",
                      "properties": {
                        "delivery_date": {
                          "type": "string",
                          "example": "YYYY-MM-DD"
                        },
                        "shipping_address_id": {
                          "type": "string"
                        },
                        "product_distribution": {
                          "type": "array",
                          "items": {
                            "type": "object",
                            "properties": {
                              "child_product_id": {
                                "type": "integer"
                              },
                              "quantity": {
                                "type": "number"
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                },
                "required": [
                  "purchase_order"
                ]
              },
              "examples": {
                "Example": {
                  "value": {
                    "purchase_order": {
                      "confirmation_mode": "erp",
                      "number": "ACME_CORP_091211",
                      "billing_address_id": 25923,
                      "request_type": "immediate",
                      "items": [
                        {
                          "child_product_id": 57062,
                          "total_quantity": 10
                        }
                      ]
                    },
                    "delivery_requests": [
                      {
                        "delivery_date": "2020-05-08",
                        "shipping_address_id": 25923,
                        "product_distribution": [
                          {
                            "child_product_id": "57062",
                            "quantity": 10
                          }
                        ]
                      }
                    ]
                  }
                }
              }
            }
          }
        }
      }
    },
    "/delivery_request_items/elastic-index": {
      "get": {
        "summary": "Get All Deliveries",
        "tags": [],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "count": {
                      "type": "number"
                    },
                    "delivery_items": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "id": {
                            "type": "string"
                          },
                          "centre_id": {
                            "type": "number"
                          },
                          "delivery_request_id": {
                            "type": "number"
                          },
                          "delivery_date": {
                            "type": "string"
                          },
                          "created_at": {
                            "type": "string"
                          },
                          "child_product_id": {
                            "type": "number"
                          },
                          "product_id": {
                            "type": "number"
                          },
                          "base_product_name": {
                            "type": "string"
                          },
                          "quantity": {
                            "type": "number"
                          },
                          "quantity_unit": {
                            "type": "string"
                          },
                          "product_image": {
                            "type": "string"
                          },
                          "purchase_order_id": {
                            "type": "number"
                          },
                          "purchase_order_number": {
                            "type": "string"
                          },
                          "delivery_request_pretty_id": {
                            "type": "string"
                          },
                          "delivery_request_shipping_address": {
                            "type": "string"
                          },
                          "delivery_request_shipping_address_details": {
                            "type": "object",
                            "properties": {
                              "id": {
                                "type": "number"
                              },
                              "alias": {
                                "type": "string"
                              },
                              "full_name": {
                                "type": "string"
                              },
                              "city": {
                                "type": "string"
                              },
                              "pincode": {
                                "type": "number"
                              }
                            }
                          },
                          "dispatch_plans": {
                            "type": "array",
                            "items": {
                              "type": "object",
                              "properties": {
                                "dispatch_plan_id": {
                                  "type": "number"
                                },
                                "shipment_id": {
                                  "type": "number"
                                },
                                "actual_quantity": {
                                  "type": "string"
                                },
                                "returned_quantity": {
                                  "type": "number"
                                },
                                "status": {
                                  "type": "string",
                                  "enum": [
                                    "dispatched",
                                    "delivered",
                                    "requested"
                                  ]
                                },
                                "status_updated_at": {
                                  "type": "string"
                                },
                                "tracking_link": {
                                  "type": "string"
                                },
                                "delivery_timeline": {
                                  "type": "object",
                                  "properties": {
                                    "deadline": {
                                      "type": "string"
                                    },
                                    "completion_date": {
                                      "type": "string"
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                },
                "examples": {
                  "Example": {
                    "value": {
                      "count": 1,
                      "delivery_items": [
                        {
                          "id": "234493",
                          "centre_id": 19470,
                          "delivery_request_id": 96289,
                          "delivery_date": "2020-06-16T00:00:00.000+05:30",
                          "created_at": "2020-05-29T15:15:25.871+05:30",
                          "child_product_id": 61018,
                          "product_id": 73439,
                          "base_product_name": "Gel Sanitizer | 500 ml",
                          "quantity": 250,
                          "quantity_unit": "Pieces",
                          "product_image": "https://d1wg0fvppk5fit.cloudfront.net/uploads/picture/image/57024/thumb_64_download__8_.jpg",
                          "purchase_order_id": 34327,
                          "purchase_order_number": "4510014006",
                          "delivery_request_pretty_id": "DR-3954-9629",
                          "delivery_request_shipping_address": "Anna Channai International Airport\nBackup Office No.3, Mezzanine Floor, 600027 , INDIA, Chennai, Tamil Nadu, India, 600027, 9967720019, , ",
                          "delivery_request_shipping_address_details": {
                            "id": 39454,
                            "alias": "Chennai Airport",
                            "full_name": "Aringar Anna",
                            "city": "Chennai",
                            "pincode": 600027
                          },
                          "dispatch_plans": [
                            {
                              "dispatch_plan_id": 163307,
                              "shipment_id": 156026,
                              "actual_quantity": "250.0",
                              "returned_quantity": 0,
                              "status": "dispatched",
                              "status_updated_at": "2020-05-29T18:13:44.605+05:30",
                              "tracking_link": null,
                              "delivery_timeline": {
                                "deadline": "2020-06-16T00:00:00.000+05:30",
                                "completion_date": null
                              }
                            }
                          ],
                          "_score": null,
                          "_explanation": null
                        }
                      ]
                    }
                  }
                }
              }
            }
          }
        },
        "operationId": "get-delivery_request_items-elastic-index",
        "parameters": [
          {
            "schema": {
              "type": "number"
            },
            "in": "query",
            "name": "page"
          },
          {
            "schema": {
              "type": "number"
            },
            "in": "query",
            "name": "per_page"
          }
        ],
        "description": "Get all deliveries in any status"
      },
      "post": {
        "summary": "",
        "operationId": "post-delivery_request_items-elastic-index",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "delivery_group_id": {
                      "type": "number"
                    }
                  }
                },
                "examples": {
                  "Example Response": {
                    "value": {
                      "delivery_group_id": 38931
                    }
                  }
                }
              }
            }
          }
        },
        "description": "Delivery requests are created in a purchase order, if a purchase order has any pending items and quantities in it",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "purchase_order_id": {
                    "type": "number"
                  },
                  "request_type": {
                    "type": "string"
                  },
                  "delivery_requests": {
                    "type": "object",
                    "required": [
                      "delivery_date",
                      "shipping_address_id",
                      "delivery_request_items"
                    ],
                    "properties": {
                      "delivery_date": {
                        "type": "string"
                      },
                      "shipping_address_id": {
                        "type": "number"
                      },
                      "delivery_request_items": {
                        "type": "array",
                        "items": {
                          "type": "object",
                          "properties": {
                            "purchase_order_item_id": {
                              "type": "string"
                            },
                            "quantity": {
                              "type": "string"
                            }
                          },
                          "required": [
                            "purchase_order_item_id",
                            "quantity"
                          ]
                        }
                      }
                    }
                  }
                },
                "required": [
                  "purchase_order_id",
                  "request_type",
                  "delivery_requests"
                ]
              },
              "examples": {
                "Example Request": {
                  "value": {
                    "purchase_order_id": 24483,
                    "request_type": "immediate",
                    "delivery_requests": [
                      {
                        "delivery_date": "2020-05-08",
                        "shipping_address_id": 14865,
                        "delivery_request_items": [
                          {
                            "purchase_order_item_id": "54206",
                            "quantity": 2
                          }
                        ]
                      }
                    ]
                  }
                }
              }
            }
          }
        }
      }
    },
    "/shipments/{shipment_id}": {
      "get": {
        "summary": "Get Shipment Data",
        "tags": [],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "core_details": {
                      "type": "object",
                      "properties": {
                        "id": {
                          "type": "number"
                        },
                        "dispatch_plan_id": {
                          "type": "number"
                        },
                        "direct_order_id": {
                          "type": "number"
                        },
                        "company_id": {
                          "type": "number"
                        },
                        "weight": {
                          "type": "number"
                        },
                        "dispatched_at": {
                          "type": "string"
                        },
                        "delivered_at": {
                          "type": "string"
                        },
                        "updated_at": {
                          "type": "string"
                        },
                        "status": {
                          "type": "string"
                        },
                        "total_amount": {
                          "type": "number"
                        },
                        "total_receivable": {
                          "type": "number"
                        },
                        "invoice_type": {
                          "type": "string"
                        },
                        "transporter": {
                          "type": "object",
                          "properties": {
                            "id": {
                              "type": "number"
                            },
                            "name": {
                              "type": "string"
                            }
                          }
                        },
                        "tracking": {
                          "type": "object",
                          "properties": {
                            "id": {
                              "type": "string"
                            },
                            "link": {
                              "type": "string"
                            },
                            "active": {
                              "type": "boolean"
                            }
                          }
                        }
                      }
                    },
                    "origin_address": {
                      "type": "object",
                      "properties": {
                        "id": {
                          "type": "number"
                        },
                        "street_address": {
                          "type": "string"
                        },
                        "landmark": {
                          "type": "string"
                        },
                        "city": {
                          "type": "string"
                        },
                        "state": {
                          "type": "string"
                        },
                        "country_id": {
                          "type": "number"
                        },
                        "pincode": {
                          "type": "number"
                        },
                        "latitude": {
                          "type": "number"
                        },
                        "mobile_number": {
                          "type": "string"
                        },
                        "state_code": {
                          "type": "string"
                        },
                        "is_active": {
                          "type": "boolean"
                        },
                        "gstin": {
                          "type": "string"
                        },
                        "gstin_attachment_id": {
                          "type": "string"
                        },
                        "auto_fetched": {
                          "type": "boolean"
                        },
                        "company_name": {
                          "type": "string"
                        }
                      }
                    },
                    "destination_address": {
                      "type": "object",
                      "properties": {
                        "id": {
                          "type": "number"
                        },
                        "street_address": {
                          "type": "string"
                        },
                        "landmark": {
                          "type": "string"
                        },
                        "city": {
                          "type": "string"
                        },
                        "state": {
                          "type": "string"
                        },
                        "country_id": {
                          "type": "number"
                        },
                        "pincode": {
                          "type": "number"
                        },
                        "latitude": {
                          "type": "number"
                        },
                        "mobile_number": {
                          "type": "string"
                        },
                        "state_code": {
                          "type": "string"
                        },
                        "is_active": {
                          "type": "boolean"
                        },
                        "gstin": {
                          "type": "string"
                        },
                        "gstin_attachment_id": {
                          "type": "string"
                        },
                        "auto_fetched": {
                          "type": "boolean"
                        },
                        "company_name": {
                          "type": "string"
                        }
                      }
                    },
                    "product_information": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "id": {
                            "type": "number"
                          },
                          "order_item_id": {
                            "type": "number"
                          },
                          "child_product_id": {
                            "type": "number"
                          },
                          "quantity": {
                            "type": "number"
                          },
                          "shipped_quantity": {
                            "type": "number"
                          },
                          "pod_quantity": {
                            "type": "number"
                          },
                          "returned_quantity": {
                            "type": "number"
                          },
                          "quantity_unit": {
                            "type": "string"
                          },
                          "product_name": {
                            "type": "string"
                          },
                          "total_amount": {
                            "type": "number"
                          },
                          "total_receivable": {
                            "type": "number"
                          }
                        }
                      }
                    },
                    "dispatch_plan_details": {
                      "type": "object",
                      "properties": {
                        "id": {
                          "type": "number"
                        },
                        "dispatch_mode": {
                          "type": "string"
                        },
                        "description": {
                          "type": "string"
                        },
                        "status": {
                          "type": "string"
                        },
                        "created_at": {
                          "type": "string"
                        }
                      }
                    },
                    "pod": {
                      "type": "object",
                      "properties": {
                        "file_url": {
                          "type": "string"
                        },
                        "uploaded_at": {
                          "type": "string"
                        },
                        "updated_at": {
                          "type": "string"
                        }
                      }
                    },
                    "invoice": {
                      "type": "object",
                      "properties": {
                        "id": {
                          "type": "number"
                        },
                        "file_url": {
                          "type": "string"
                        },
                        "number": {
                          "type": "string"
                        },
                        "date": {
                          "type": "string"
                        },
                        "buyer_service_bill_number": {
                          "type": "string"
                        }
                      }
                    }
                  }
                },
                "examples": {
                  "Example Shipment Data": {
                    "value": {
                      "core_details": {
                        "id": 81734,
                        "dispatch_plan_id": 89347,
                        "direct_order_id": 55996,
                        "company_id": 15574,
                        "weight": 0,
                        "dispatched_at": "Jul 19, 2019",
                        "delivered_at": "Jul 21, 2019",
                        "created_at": "2019-07-19T16:13:40.432+05:30",
                        "updated_at": "2019-08-12T17:44:55.974+05:30",
                        "status": "delivered",
                        "total_amount": 8142,
                        "total_receivable": 8142,
                        "invoice_type": "inv",
                        "transporter": {
                          "id": 422,
                          "name": "DTDC"
                        },
                        "tracking": {
                          "id": "100003199727",
                          "link": null,
                          "active": false
                        }
                      },
                      "origin_address": {
                        "id": 15343,
                        "street_address": "Somewhere in the earth",
                        "landmark": null,
                        "city": "Bangalore",
                        "state": "Karnataka",
                        "country_id": 105,
                        "pincode": 562123,
                        "latitude": null,
                        "longitude": null,
                        "mobile_number": "9820098200",
                        "state_code": "KA",
                        "is_active": true,
                        "gstin": "29AAVCG045D2ZV",
                        "gstin_attachment_id": null,
                        "auto_fetched": false,
                        "vat": null,
                        "cst": null,
                        "gstin_state_code": "29",
                        "alias": "",
                        "centre_id": null,
                        "full_name": "Bangalore",
                        "company_name": "SMARTPADDLE TECHNOLOGY PRIVATE LIMITED",
                        "user_id": null,
                        "is_billing": true,
                        "addressable_id": 11,
                        "addressable_type": "Warehouse",
                        "country": "India",
                        "created_at": "2018-11-12T16:30:23.411+05:30",
                        "updated_at": "2019-11-26T16:21:01.651+05:30",
                        "buyer_warehouse_code": null,
                        "mobile_number_country_id": 105,
                        "landline_number": null,
                        "alternate_number": null,
                        "nearest_warehouse_id": null
                      },
                      "destination_address": {
                        "id": 17131,
                        "cst": "",
                        "vat": "",
                        "city": "Bangalore",
                        "alias": "Shipping Address",
                        "gstin": "29AAICA3918J1ZE",
                        "state": "Karnataka",
                        "country": "India",
                        "pincode": 560067,
                        "user_id": 31086,
                        "landmark": null,
                        "latitude": null,
                        "centre_id": 15117,
                        "full_name": "Roadrunner Ramamurthy",
                        "is_active": true,
                        "longitude": null,
                        "contact_id": null,
                        "created_at": "2019-03-27T11:09:18.094+05:30",
                        "state_code": "KA",
                        "updated_at": "2019-05-29T14:19:49.657+05:30",
                        "auto_fetched": false,
                        "company_name": "Acme Corporation",
                        "mobile_number": "+919822098200",
                        "addressable_id": null,
                        "street_address": "ACME - Somewhere on the earth",
                        "addressable_type": null,
                        "gstin_state_code": "29",
                        "gstin_attachment_id": null
                      },
                      "product_information": [
                        {
                          "id": 157471,
                          "order_item_id": 121376,
                          "child_product_id": null,
                          "quantity": 3000,
                          "shipped_quantity": 3000,
                          "pod_quantity": 0,
                          "returned_quantity": 0,
                          "quantity_unit": "Pieces",
                          "product_name": "Gift Card | 9.2 cm X 16.6 cm",
                          "total_amount": 8142,
                          "total_receivable": 8142
                        }
                      ],
                      "dispatch_plan_details": {
                        "id": 89347,
                        "dispatch_mode": "warehouse_to_buyer",
                        "description": "Create by system",
                        "status": "done",
                        "created_at": "2019-07-18T12:09:45.584+05:30"
                      },
                      "pod": {
                        "file_url": "https://supplychain-production.s3.amazonaws.com/uploads/shipment/buyer_pod_file/81734/1563817650_buyer_pod_file.jpeg",
                        "uploaded_at": null,
                        "updated_at": "2019-07-22T23:17:30.105+05:30"
                      },
                      "invoice": {
                        "id": 70229,
                        "file_url": "https://supplychain-production.s3.amazonaws.com/uploads/invoice/buyer_invoice_file/7229/13533024_buyer_tax_invoice_89347.pdf",
                        "number": "GSPKA/FY20/0239",
                        "date": "2019-07-19T16:13:40.700+05:30",
                        "buyer_service_bill_number": null
                      },
                      "delivery_challan": {
                        "file_url": null,
                        "number": null
                      },
                      "credit_note": {
                        "file_url": null,
                        "number": null,
                        "date": null,
                        "amount": null,
                        "return_shipment_id": null
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "operationId": "get-shipments",
        "description": "Shipment information is available using the shipment ID, if it is created. Shipment ID can be retrieved in the GET call of delivery request items' dispatch plan object."
      },
      "parameters": [
        {
          "schema": {
            "type": "number"
          },
          "name": "shipment_id",
          "in": "path",
          "required": true
        }
      ]
    }
  },
  "components": {
    "schemas": {}
  }
}